# Default values for todos-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/appvia/todos-app
  pullPolicy: IfNotPresent
  tag: "sha-777555b550e290fa7c6be050957b6e906492bad4"

env:
 - name: DB_NAME
   value: todos

envSecrets:
 - name: DB_HOST
   secretName: aws-rds-postgresql-database-outputs
   secretKey: db_instance_address
 - name: DB_USERNAME
   secretName: aws-rds-postgresql-database-outputs
   secretKey: db_instance_username
 - name: DB_PASSWORD
   secretName: aws-rds-postgresql-database-outputs
   secretKey: db_instance_password

nameOverride: ""
fullnameOverride: ""
securityContext:
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: prod-le-dns01
  hosts:
    - host: todos.wsa-eks-np-dev.apps.demo.wf.appvia.io
      paths:
      - path: /
        backend:
          serviceName: todos-app
          servicePort: 8080
  tls:
   - secretName: todos-tls
     hosts:
       - todos.wsa-eks-np-dev.apps.demo.wf.appvia.io

resources: {}
