name: Publish Helm Chart
on:
  push:
    paths:
      - 'charts/todos-app/*'


env:
  HELM_EXPERIMENTAL_OCI: 1
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/todos-app

jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - name: install helm
        uses: Azure/setup-helm@v1

      - name: Login to GitHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Helm Chart
        run: |
          helm chart save ${{ github.workspace }}/charts/todos-app/ ${{ env.GCR_IMAGE }}:${{ github.sha }}

      - name: Publish Helm Chart
        run: |
          helm chart push ${{ env.GCR_IMAGE }}:${{ github.sha }}
